### ISSUE TITLE
Can't abort failed simulation

### ISSUE THREAD

**Issue by jchodera** [peastman/openmm-setup#8]
I tried running a simulation using a PDB from the RCSB, and got the error message
```
Building system...
Process Process-1:
Traceback (most recent call last):
  File "/Users/choderaj/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/choderaj/miniconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/choderaj/github/pandegroup/openmm-setup/openmm-setup/openmm-setup.py", line 172, in simulate
    exec(script, {"output":output, "outputDir":outputDir})
  File "<string>", line 58, in <module>
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 1069, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (MET).  The set of atoms is similar to MET, but it is missing 9 hydrogen atoms.
```
Meanwhile, the console filled up with
```
127.0.0.1 - - [22/Nov/2016 19:13:38] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:41] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:43] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:45] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:46] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:48] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:51] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:53] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:54] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:57] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:13:59] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:01] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:03] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:05] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:07] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:09] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:11] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:13] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:15] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:17] "GET /getSimulationOutput HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:19] "GET /getSimulationOutput HTTP/1.1" 200 -
```
and clicking the "Cancel" button emitted
```
127.0.0.1 - - [22/Nov/2016 19:14:27] "POST /stopSimulation HTTP/1.1" 200 -
127.0.0.1 - - [22/Nov/2016 19:14:28] "GET /getSimulationOutput HTTP/1.1" 404 -
```
but hasn't brought me back to another useful page.

**Comment by peastman** [comment]
Just close the tab.  When you click "Run Simulation", it opens a new tab.

Those GET requests are the browser polling the server to get the latest output from the simulation.  When it returns 404, that signals that there's no more output and it should stop polling.  It should have done that automatically after the exception was thrown, though.  I don't know why it didn't.

**Comment by jchodera** [comment]
> Just close the tab. When you click "Run Simulation", it opens a new tab.

Ah! You might have "Cancel" print something like "Job cancelled. You may now safely close this tab."
